language: python
python:
- 3.6
install:
- pip install --upgrade --force-reinstall setuptools
- pip uninstall --yes yabc || true
- pip install --upgrade --force-reinstall --ignore-installed -e .
script:
- python setup.py test
- make run& sleep 5; make test_all
