language: python
install:
- pip install --upgrade --force-reinstall setuptools
- pip uninstall --yes yabc || true
- pip install --upgrade --force-reinstall --ignore-installed -e .
script:
- PYTHONPATH=tests python setup.py test
- make nuke_db_and_run& sleep 5; make test_all
branches:
  only:
    - master
matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
