language: python
install:
- pip install --upgrade --force-reinstall setuptools
- pip uninstall --yes yabc || true
- pip install --upgrade --force-reinstall --ignore-installed -e .
script:
- python setup.py test
- make nuke_db_and_run& sleep 5; make test_all
- python -m yabc testdata/gemini/sample_gemini.csv ./testdata/coinbase/sample_coinbase.csv
branches:
  only:
    - master
matrix:
  include:
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8-dev
      dist: xenial
      sudo: true
