language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
- pip install --upgrade --force-reinstall setuptools
- pip uninstall --yes yabc || true
- pip install --upgrade --force-reinstall --ignore-installed -e .
script:
- PYTHONPATH=tests python setup.py test
- make nuke_db_and_run& sleep 5; make test_all
- python -m yabc testdata/gemini/sample_gemini.xlsx ./testdata/coinbase/sample_coinbase.csv
branches:
  only:
    - master
